port = "2224"
username = "deploy"
password = "forever"
pidfile = "/etc/goforever/goforever.pid"
logfile = "/etc/goforever/goforever.log"
errfile = "/etc/goforever/goforever.log"

[[process]]
name = "postgresql"
command = "/usr/bin/pg_ctlcluster"
args = [ "9.3", "main", "start" ]
pidfile = "/etc/goforever/postgresql/postgresql.pid"
logfile = "/etc/goforever/postgresql/logs/postgresql.debug.log"
errfile = "/etc/goforever/postgresql/logs/postgresql.errors.log"
respawn = 1
delay = "1m"
ping = "30s"

[[process]]
name = "sshd"
command = "/usr/local/bin/runsshd"
args = [ "-D" ]
pidfile = "/etc/goforever/sshd/sshd.pid"
logfile = "/etc/goforever/sshd/logs/sshd.debug.log"
errfile = "/etc/goforever/sshd/logs/sshd.errors.log"
respawn = 1
delay = "1m"
ping = "30s"


